"""'initialmigration'

Revision ID: 383eeefed4a7
Revises: 
Create Date: 2019-08-08 00:21:38.826596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '383eeefed4a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    op.drop_index('public_id', table_name='user')
    op.drop_index('username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('registered_on', mysql.DATETIME(), nullable=False),
    sa.Column('admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('public_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_index('username', 'user', ['username'], unique=True)
    op.create_index('public_id', 'user', ['public_id'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
